workflows:
  ios-app-build:
    name: Budowa aplikacji iOS
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      xcode: latest
    scripts:
      - name: Pobieranie i wymuszenie certyfikatów
        script: |
          app-store-connect fetch-signing-files "com.fhi.my" --type IOS_APP_STORE --create
      - name: Inicjalizacja pęku kluczy
        script: |
          keychain initialize
          keychain add-certificates
      - name: Generowanie projektu (xcodegen)
        script: |
          brew install xcodegen
          xcodegen generate
      - name: Przypisanie profili do projektu
        script: |
          xcode-project use-profiles
      - name: Budowa aplikacji
        script: |
          xcode-project build-ipa --project "MyApp.xcodeproj" --scheme "MyApp"
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
