name: MyApp
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [MyApp]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fhi.my
        CODE_SIGN_STYLE: Manual
